### ISSUE TITLE
Potential feature: auto rename duplicate file names 

### ISSUE THREAD

**Issue by Meimec** [ThorpeJosh/image-sorting-tool#17] opened 2021-02-17 21:13 UTC
Congrats to the nice and useful tool! 
Just one thing I struggled with: Since some pictures might have the same time stamp (taken within the same second), they get overwritten when sorting by the last picture having the file name corresponding to this second. 

BR

**Comment by ThorpeJosh** [comment] 2021-02-20 01:10
Hi thanks for giving it a try!

This was by design as I had lots of datasets that I knew were full of duplicates due to years of poor media management.
Due to the parallel processing of the media files it makes it a little bit more complicated to handle duplicates as everything is sorted out of order but shouldn't be too hard to add options on ways to handle duplicates.

What is better:
1.  Rename duplicates <new_name>_1.extension?
2. Copy them to a duplicates folder instead of overwriting so you can see what was duplicated (similair to "failed_to_sort" or "other" files)?

Cheers

**Comment by Meimec** [comment] 2021-02-20 10:29
Hi Josh! 

 

I used the script for exactly the same reason: to clean up the mess created during years. And: it does an awesome and super-fast job. 
The issue with the duplicates is mainly caused by serial pictures taken when using the burst function of the camera. 

 

Quickly tried to hack in the lines to auto-rename the duplicates myself (see below) but, as you mentioned: out of 20 files, some 2-4 get overwritten due to parallel task handling, which I’m not yet experienced enough in coding to deal with. 

 

My personal preference would be option 1: “Rename duplicates <new_name>_1.extension” 



Regards from the Swiss Alps! 

Chris

 

******************************************************************************

temp_new_name = "{}{}{}_{}{}{}{}{}".format(

                str(dtime.year).zfill(4),

                str(dtime.month).zfill(2),

                str(dtime.day).zfill(2),

                str(dtime.hour).zfill(2),

                str(dtime.minute).zfill(2),

                str(dtime.second).zfill(2),

                '',

                os.path.splitext(source_image_path)[1],

            )

            new_path = os.path.join(

                destination_dir, str(dtime.year).zfill(4), str(dtime.month).zfill(2)

            )

            os.makedirs(new_path, exist_ok=True)

 

            i = 0

            while os.path.exists(os.path.join(new_path,temp_new_name)):

                i += 1

                name, ext = os.path.splitext(temp_new_name)

                temp_new_name = name[:15] + '_' +str(i) + ext

 

            new_name = os.path.basename(temp_new_name)

**Comment by ThorpeJosh** [comment] 2021-02-21 15:53
Hi Chris, 
I've been without internet for several days now (greetings from Australia via our National Broadband Network). What you've done would have been my first attempt. But if what you said is true then between the time a thread checks if the temp name exists but before writing the file, another thread checks and thinks the file doesn't exist yet.

The better solution is to share a set of filenames between all the threads and check if the filename exists in the set and add the filename to the set before writing the file to disk.

My phone doesn't take burst shots so I'll have to find some on the web to test with.

I'll see how I go and post back.
Feel free to make a pull request too if you have any luck.

This blog has a decent explanation of how I perform multiprocessing with a pool of workers to sort the images. 1st example is identical.
https://www.codesdope.com/blog/article/multiprocessing-using-pool-in-python/

**Comment by Meimec** [comment] 2021-02-22 09:47
Hi Josh, 

 

Fun to hear that the network in AU is still an issue – remember that same experience/pain when staying in Karatha / Dampier. 

 

Thanks for the thorough explanation and the interesting proposal for an approach to get it implemented. I’ll see if I find time to work on it the next days. 

 

Cheers!

**Comment by ThorpeJosh** [comment] 2021-02-25 11:54
Hi Chris,

Karratha is a long way from anywhere. I just had 5 days with no internet (broadband or mobile, complete blackout) only 50km from Melbourne. Fun times. I was spoilt with fast reliable internet in Stuttgart when I worked there and also in Singapore, so I get more frustrated with AU internet than most Aussies do.

I have added this feature to the GUI and passed the checkbox boolean through to the sorting function that runs in each thread. It is ready for your changes. It is on a "duplicates" branch: github.com/ThorpeJosh/image-sorting-tool/pull/19
I am still unsure the best way to go about each worker/thread communicating so they don't simultaneously choose and write the same filename.

**Comment by ThorpeJosh** [comment] 2023-10-23 11:45
@Meimec Hope you're well.

Almost 3 years later but this should now be implemented in the [latest release ](https://github.com/ThorpeJosh/image-sorting-tool/releases/tag/1.0.0). [PyPI Link](https://pypi.org/project/image-sorting-tool/)

I'll close this issue but if you still run into issues with this new feature, please reopen.

**Closed by ThorpeJosh** 2023-10-23 11:45 UTC
Labels: enhancement
